"""empty message

Revision ID: 0c73ae3a75b7
Revises: dd26e26bbb0d
Create Date: 2025-11-20 19:18:16.513941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c73ae3a75b7'
down_revision = 'dd26e26bbb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='订阅记录ID，主键自增'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='订阅学生ID'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='被订阅课程ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribe_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribe_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribe_student_id'))
        batch_op.drop_index(batch_op.f('ix_subscribe_course_id'))

    op.drop_table('subscribe')
    # ### end Alembic commands ###
