"""empty message

Revision ID: 0fa4f23f9154
Revises: 1488e913c435
Create Date: 2025-11-26 21:40:24.158032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa4f23f9154'
down_revision = '1488e913c435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='广告ID，主键自增'),
    sa.Column('link', sa.Text(), nullable=False, comment='广告跳转链接'),
    sa.Column('image', sa.Text(), nullable=False, comment='广告图片存储路径'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='广告名称'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement')
    # ### end Alembic commands ###
