"""empty message

Revision ID: 1488e913c435
Revises: 64956f3454a0
Create Date: 2025-11-22 14:17:32.840010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1488e913c435'
down_revision = '64956f3454a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'))
        batch_op.drop_index(batch_op.f('ix_play_progress_student_id'))
        batch_op.create_index(batch_op.f('ix_play_progress_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='订阅学生ID'))
        batch_op.drop_index(batch_op.f('ix_play_progress_user_id'))
        batch_op.create_index(batch_op.f('ix_play_progress_student_id'), ['student_id'], unique=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
