"""empty message

Revision ID: 15266a49b34e
Revises: ef8af7436d4c
Create Date: 2025-12-07 15:18:43.341061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15266a49b34e'
down_revision = 'ef8af7436d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='问评论ID，主键自增'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('image', sa.Text(), nullable=True, comment='评论图片存储地址，可选'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='问题创建时间，默认为当前时间'),
    sa.Column('likes', sa.Integer(), nullable=False, comment='问题点赞数，默认为0'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='关联课程ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='评论用户ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID，comment_type为1时取值为-1'),
    sa.Column('comment_type', sa.Integer(), nullable=False, comment='评论类型，1为楼，2为层，3为对层的评论'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_course_id'))

    op.drop_table('comment')
    # ### end Alembic commands ###
