"""empty message

Revision ID: 363a562a8834
Revises: 0fa4f23f9154
Create Date: 2025-12-01 14:17:51.540907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363a562a8834'
down_revision = '0fa4f23f9154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏记录ID，主键自增'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='学生ID'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_student_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_course_id'))

    op.drop_table('favorites')
    # ### end Alembic commands ###
