"""empty message

Revision ID: 425882684f44
Revises: 
Create Date: 2025-10-25 15:49:03.185393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425882684f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学生信息ID，主键自增'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='学生年级，如：六年级、初一、高三等'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='讲师信息ID，主键自增'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='讲师ID'),
    sa.Column('university', sa.String(length=20), nullable=True, comment='毕业院校'),
    sa.Column('introduction', sa.Text(), nullable=True, comment='自我介绍'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID，主键自增'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='用户邮箱，唯一'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=300), nullable=False, comment='加密后的密码'),
    sa.Column('join_time', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='头像URL路径，默认使用系统头像'),
    sa.Column('role', sa.Integer(), nullable=False, comment='用户身份，0为学生，1为讲师，2为管理员'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('teacher_information')
    op.drop_table('student_information')
    # ### end Alembic commands ###
