"""empty message

Revision ID: 5f24a17eb549
Revises: ef5a10546cbb
Create Date: 2025-11-10 15:11:13.563426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f24a17eb549'
down_revision = 'ef5a10546cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='课程ID，主键自增'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='课程名称'),
    sa.Column('cover', sa.Text(), nullable=True, comment='封面URL路径，默认使用系统封面'),
    sa.Column('introduction', sa.Text(), nullable=False, comment='课程简介'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='课程创建时间'),
    sa.Column('course_folder', sa.Text(), nullable=False, comment='课程文件夹'),
    sa.Column('price', sa.Float(), nullable=False, comment='订阅价格（单位：元）'),
    sa.Column('teacher_id', sa.Integer(), nullable=True, comment='授课教师ID'),
    sa.Column('subject_id', sa.Integer(), nullable=True, comment='所属学科ID'),
    sa.Column('grade_id', sa.Integer(), nullable=True, comment='适用年级ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='年级ID，主键自增'),
    sa.Column('name', sa.String(length=10), nullable=False, comment='年级名称，如：一年级、初二、高三等'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='学科ID，主键自增'),
    sa.Column('name', sa.String(length=10), nullable=False, comment='学科名称，如：数学、语文、英语、物理、化学等'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('grade')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_course_subject_id'))
        batch_op.drop_index(batch_op.f('ix_course_grade_id'))

    op.drop_table('course')
    # ### end Alembic commands ###
