"""empty message

Revision ID: 64956f3454a0
Revises: 0c73ae3a75b7
Create Date: 2025-11-22 13:36:23.677603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64956f3454a0'
down_revision = '0c73ae3a75b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID，自增'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='订阅学生ID'),
    sa.Column('video_id', sa.Integer(), nullable=True, comment='视频ID'),
    sa.Column('progress', sa.Float(), nullable=True, comment='播放进度'),
    sa.Column('last_updated', sa.DateTime(), nullable=False, comment='上次更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_progress_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_play_progress_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_progress_video_id'))
        batch_op.drop_index(batch_op.f('ix_play_progress_student_id'))

    op.drop_table('play_progress')
    # ### end Alembic commands ###
