"""empty message

Revision ID: a2eb6d01b0ad
Revises: 5f24a17eb549
Create Date: 2025-11-11 14:43:22.010655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2eb6d01b0ad'
down_revision = '5f24a17eb549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='章节ID，主键自增'),
    sa.Column('title', sa.Text(), nullable=False, comment='章节标题'),
    sa.Column('order', sa.Integer(), nullable=False, comment='顺序'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='所属课程ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_course_id'))

    op.drop_table('chapter')
    # ### end Alembic commands ###
