"""empty message

Revision ID: a89d4678d729
Revises: 15266a49b34e
Create Date: 2025-12-09 14:40:09.084862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89d4678d729'
down_revision = '15266a49b34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='点赞记录ID'),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='评论ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='点赞时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index('idx_user_comment', ['user_id', 'comment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index('idx_user_comment')

    op.drop_table('like')
    # ### end Alembic commands ###
