"""empty message

Revision ID: dd26e26bbb0d
Revises: a2eb6d01b0ad
Create Date: 2025-11-12 14:43:57.293459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd26e26bbb0d'
down_revision = 'a2eb6d01b0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文档ID，主键自增'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='文档标题'),
    sa.Column('file', sa.Text(), nullable=False, comment='文档文件存储路径'),
    sa.Column('chapter_id', sa.Integer(), nullable=True, comment='所属章节ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='视频ID，主键自增'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='视频标题'),
    sa.Column('file', sa.Text(), nullable=False, comment='视频文件存储路径'),
    sa.Column('order', sa.Integer(), nullable=False, comment='顺序'),
    sa.Column('chapter_id', sa.Integer(), nullable=False, comment='所属章节ID，外键关联chapter表'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_chapter_id'), ['chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_chapter_id'))

    op.drop_table('video')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chapter_id'))

    op.drop_table('document')
    # ### end Alembic commands ###
