"""empty message

Revision ID: ef5a10546cbb
Revises: 425882684f44
Create Date: 2025-10-27 21:51:00.419682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5a10546cbb'
down_revision = '425882684f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID，自增'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='用户邮箱地址，不可为空'),
    sa.Column('invitation_code', sa.String(length=10), nullable=False, comment='10位邀请码，不可为空'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='邀请码创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_code')
    # ### end Alembic commands ###
