"""empty message

Revision ID: ef8af7436d4c
Revises: 363a562a8834
Create Date: 2025-12-02 16:37:50.238724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef8af7436d4c'
down_revision = '363a562a8834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_record',
    sa.Column('id', sa.String(length=100), nullable=False, comment='支付记录ID，主键'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程ID'),
    sa.Column('course_name', sa.String(length=100), nullable=False, comment='课程名称'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='学生ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='支付金额（单位：元）'),
    sa.Column('time', sa.DateTime(), nullable=False, comment='支付时间，默认为当前时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_record_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_record_student_id'))

    op.drop_table('payment_record')
    # ### end Alembic commands ###
